### ISSUE TITLE
Packages tagged `main-distribution` included in search results by default

### ISSUE THREAD

**Issue by jsmaniac** [tonyg/racket-pkg-website#22]
The old http://pkgs.racket-lang.org/ excluded packages with the tags `main-distribution`, `main-tests` and `deprecated` by default. The new manager excludes only `main-distribution` in the default display, and includes everything when doing a search.

Feel free to close this as wontfix, I just was not sure if this new behaviour was intentional or not.

Also, perhaps there should be a small notice somewhere about the packages from main-distribution being excluded by default (and a link to include them?). The old manager had the three tags typeset with strike-through, which indicated what was excluded by default.

**Comment by tonyg** [comment]
I've hidden the other two tags as you suggested, and added a "(see all)" link next to the package count on the main page. Do you think this goes far enough? I'll tentatively close this; please feel free to comment/reopen if you have more suggestions in this area! Thanks for the input.

**Comment by jsmaniac** [comment]
Seems great to me, good for closing, thanks!
