### ISSUE TITLE
Auto-login stopped working + shorter session timeout

### ISSUE THREAD

**Issue by jsmaniac** [tonyg/racket-pkg-website#25]
Roughly since the URL became https://pkgn.racket-lang.org/, I started noticing the following issues:
- When accessing the page, it often does not automatically log me in, but if I click the "Login" button in the top right corner it logs me in without the need to type a password. It should instead detect that I'm logged in from the start.
- The session timeout seems shorter than before (or is not updated by page visits). I access the https://pkgn.racket-lang.org/ page several times a day and updated my packages after I pushed some new commits, but sometimes when accessing the page have to re-login by typing my password (before it mostly happened after the service was re-started). Can we have a longer timeout? I wouldn't mind typing in my password after a week of activity, but a day (or less?) seems a bit short.

**Comment by tonyg** [comment]
These are good suggestions. I'm going to close this, and open two new bugs, one for auto-login from the static pages, and one for improving the way session expiry works.
