### ISSUE TITLE
Switch DNS over pkgn-->pkgs

### ISSUE THREAD

**Issue by tonyg** [tonyg/racket-pkg-website#34]
cc @samth

This also entails fiddling with the config on pkgd to fix up the URLs so they don't have the `/pkgn/` in them.

**Comment by jeapostrophe** [comment]
- [ ] What config files need to change?
- [ ] Stop the server
- [ ] Update the config files
- [ ] Rename the buckets
- [ ] Start the server

**Comment by jeapostrophe** [comment]
@tonyg please confirm this plan

**Comment by jeapostrophe** [comment]
@tonyg I'm going to execute this plan in about a week, so please confirm it if you can.

**Comment by tonyg** [comment]
I've not yet reviewed the plan in detail (but in broad outline it looks good!), but wanted to ask whether we need to resolve #40 properly before we switch over, since that might affect the actual operation of the catalog, rather than just the UI.

**Comment by jeapostrophe** [comment]
Almost everything is working. There are a few problems:

- [ ] http://pkgn.racket-lang.org is failing because of a bucket/CNAME mismatch. I have an idea for how to fix this
- [ ] changes to files are not yet committed
