### ISSUE TITLE
The `formica` package is continuously marked "recently updated"

### ISSUE THREAD

**Issue by jackfirth** [tonyg/racket-pkg-website#54]
According to [the formica github repo](https://github.com/samsergey/formica/tree/master) it hasn't been updated in 5 years, but the [package catalog entry](https://pkgs.racket-lang.org/package/formica) seems to think it's being updated every night.

**Comment by jeapostrophe** [comment]
The package has an error, so the server tries to update it in case things are now fixed (i.e. the error was transient on the side of the server, like losing the network connection) and the "updated recently" really means "The package server updated the entry" not "The checksum is different than last time."

**Comment by jackfirth** [comment]
That means if I sort packages by recently updated, I'll see the same dozen packages that fail to build and haven't been touched by their creators in years.

**Comment by jeapostrophe** [comment]
I changed it to only say it updated if the checksums are different.
