### ISSUE TITLE
The "versions" field is misleading

### ISSUE THREAD

**Issue by jackfirth** [tonyg/racket-pkg-website#55]
The "Versions" field for editing a package implies its for specifying multiple different versions of the same package, and that a user can somehow pick a specific version to install / depend on or constrain the version using some semver-like system. But it's actually for [version exceptions](https://docs.racket-lang.org/pkg/getting-started.html#%28part._.Version_.Exceptions%29) which provide different versions of the same package based on what *Racket version* a client is using. There are some packages who have confused it for the former, including the [herbie package](https://pkgs.racket-lang.org/package/herbie) with "1.0" and "1.1" versions (which will never be used). Changing the field name to "Version exceptions" and maybe making it link to the appropriate docs about version exceptions might help.

**Comment by jeapostrophe** [comment]
Done, thanks.
