### ISSUE TITLE
undefined in "Create a new package"

### ISSUE THREAD

**Issue by sorawee** [tonyg/racket-pkg-website#63]
A picture is worth a thousand words

![screenshot from 2018-03-08 18-58-46](https://user-images.githubusercontent.com/9099577/37183208-e6b59e7e-2302-11e8-8619-48a3a214963f.png)

**Comment by greghendershott** [comment]
Sorry for the drive-by back-seat commentary but I happened to notice this and get curious how the site worked. From what I could figure out:

It looks like commit 180e0c9a "Remove support for unencrypted git transports. (git:// and http://)" by @technomancy maybe also needed to update `static/editpackage.js`?

It seems like a quick, safe hack could be to replace `pieces[1]` with a hardcoded `'https'` [here](https://github.com/tonyg/racket-pkg-website/blob/master/static/editpackage.js#L37)?

(A more-thorough cleanup would be to remove that element form `pieces`, shift all the other indexes -- and try not to make a new bug.)

**Comment by jeapostrophe** [comment]
Thanks for the report and thanks for the pointer Greg. I'm going with the safe thing for now.
